server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
<<<<<<< HEAD
    url: jdbc:oracle:thin:@localhost:1521:XE
=======
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:XE
>>>>>>> 4c170c2b8ba36b7a04f3dc1a13c2fd927f9c8d47
    username: C##HIGHCARE
    password: HIGHCARE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/images/
<<<<<<< HEAD
=======
  # cookie
  server:
    servlet:
      session:
        cookie:
          same-site: none
          secure: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hdhye89@gmail.com
    password: aedelgcwhhiexqpt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
>>>>>>> 4c170c2b8ba36b7a04f3dc1a13c2fd927f9c8d47
  # redis cache config
  redis:
    host: localhost
    port: 6379
<<<<<<< HEAD
  # jpa config
=======
# jpa config
>>>>>>> 4c170c2b8ba36b7a04f3dc1a13c2fd927f9c8d47
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate:
        '[format_sql]': true
<<<<<<< HEAD
# jwt secret key
jwt:
  secret: EBWJJG+CWIAKltusVjf9SL0pEfOL9xWvLnu2vClsYx7kZLH0t3R6jLCjE7OB1Jq45yIxOd3wa73/obPVhVosyQ==
  expire-time: 3600000 # 1시간(밀리초 단위)
=======
    hibernate:
      use-new-id-generator-mappings: true
# jwt secret key
jwt:
  secret: EBWJJG+CWIAKltusVjf9SL0pEfOL9xWvLnu2vClsYx7kZLH0t3R6jLCjE7OB1Jq45yIxOd3wa73/obPVhVosyQ==
  expire-time: 100000 # (밀리초 단위)
  refresh-expire-time: 1000000

>>>>>>> 4c170c2b8ba36b7a04f3dc1a13c2fd927f9c8d47
  # logging config
  logging:
    level:
      root: info
image:
  add-resource-locations: classpath:/static/images/
  add-resource-handler: /images/**

  image-dir: src/main/resources/static/images
  image-url: http://localhost:8080/images/
<<<<<<< HEAD
=======

>>>>>>> 4c170c2b8ba36b7a04f3dc1a13c2fd927f9c8d47
